### ISSUE TITLE
Expected directory layout unclear

### ISSUE THREAD

**Issue by arghdos** [OfekShilon/optview2#14]
From the `argparse` help text:
```
positional arguments:
  yaml_dirs_or_files    List of optimization record files or directories searched for optimization record files.
```
I would expect that I could just call `opt-viewer.py some_file.opt.yaml`.  However, if you do so and do not set `split_top_folders`, you end up in https://github.com/OfekShilon/optview2/blob/main/opt-viewer.py#L450, which results in no work being done, as `subfolders` is identically `[""]`.  This mostly implies that `split_top_folders` is indeed, not optional.

**Comment by arghdos** [comment]
Through experimentation, I've discovered that the script seems to want:  
```
topdir/subdir/whatever.opt.yaml  
```
if this is by design, it should be documented.  Personally, I would prefer the option to simply pass in `whatever.opt.yaml` as a positional arg.

**Comment by OfekShilon** [comment]
Thank you!  Will look into it in the near few days.

**Comment by OfekShilon** [comment]
@arghdos  I'm afraid I'm unable to reproduce. Can you please specify -
(1) An exact source repo I can clone,
(2) Your exact build (command line or script modification
(3) Your exact arguments to opt-viewer.py?

**Comment by OfekShilon** [comment]
@arghdos  fixed
